---
trailingComma: 'all'
# tabWidth: 4
semi: true
singleQuote: true
bracketSpacing: true
arrowParens: 'always'
# overrides:
#   - files: ['*.json', '*.html', '*.css']
#     options:
#       semi: false
#       tabWidth: 2
